apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: synerunify-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: synerunify-virtualservice
  namespace: synerunify
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingress/synerunify-gateway
  http:
    - match:
        - uri:
            prefix: /system
      route:
        - destination:
            host: system-server.synerunify.svc.cluster.local
            port:
              number: 9000
    - match:
        - uri:
            prefix: /captcha
      route:
        - destination:
            host: captcha-service.synerunify.svc.cluster.local
            port:
              number: 8080
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-captcha-manage
  namespace: synerunify
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
    - to:
        - operation:
            paths: ["/captcha/manage", "/captcha/manage/*"]