---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tesseract
  namespace: synerunify
  labels:
    app: tesseract
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesseract
  template:
    metadata:
      labels:
        app: tesseract
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: tesseract
          image: 'synerunify/tesseract'
          ports:
            - name: tcp-8012
              containerPort: 8012
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
...
---
kind: Service
apiVersion: v1
metadata:
  name: tesseract
  namespace: synerunify
  labels:
    app: tesseract
spec:
  ports:
    - name: tcp-8012
      protocol: TCP
      port: 8012
      targetPort: 8012
      nodePort: 8012
  selector:
    app: tesseract
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
...