---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-captcha
  namespace: synerunify
  labels:
    app: service-captcha
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-captcha
  template:
    metadata:
      labels:
        app: service-captcha
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: service-captcha
          image: 'synerunify/service-captcha'
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
            - name: grpc-50051
              containerPort: 50051
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
...
---
kind: Service
apiVersion: v1
metadata:
  name: service-captcha
  namespace: synerunify
  labels:
    app: service-captcha
spec:
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 9020
    - name: grpc-50051
      protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 9021
  selector:
    app: service-captcha
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
...