# build logger
FROM rust AS build-logger

RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

WORKDIR /app

COPY ./ ./

RUN cd . && \
    cargo build --release --lib logger-server \

# build final
FROM scratch

WORKDIR /app

COPY --from=build-logger /app/target/release/logger-server ./logger-server
COPY --from=build-logger /app/regexes.yaml ./regexes.yaml

EXPOSE 9010

CMD ["/app/logger-server"]