# build erp
FROM rust AS builder

RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

WORKDIR /app

COPY ./ ./

RUN cd . && \
    cargo build --release --bin erp-server

# build final
FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libssl3

COPY --from=builder /app/target/release/erp-server ./erp-server
COPY --from=builder /app/regexes.yaml ./regexes.yaml

EXPOSE 8080

CMD ["/app/erp-server"]