# build system
FROM rust AS builder

RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

WORKDIR /app

COPY ./ ./

RUN cd . && \
    cargo build --release --bin system-server

# build final
FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libssl3

COPY --from=builder /app/target/release/system-server ./system-server
COPY --from=builder /app/regexes.yaml ./regexes.yaml

EXPOSE 9000

CMD ["/app/system-server"]