apiVersion: v1
kind: ConfigMap
metadata:
  name: synerunify-config
  namespace: synerunify
data:
  DATABASE_URL: 'mysql://synerunify:synerunify@mysql.synerunify-base.svc:3306/synerunify'
  REDIS_URL: 'redis://default:synerunify@redis.synerunify.svc:6379/'
  MONGO_URL: 'mongodb://synerunify:synerunify@mongo.synerunify.svc:27017'
  MINIO_URL: 'http://minio.synerunify.svc:9000'
  MINIO_ACCESS_KEY: 'synerunify'
  MINIO_SECRET_KEY: 'synerunify'
  LOG_LEVEL: 'info'
  GRPC_CAPTCHA_SERVICE_URL: 'http://service-captcha.synerunify.svc:50051'